import "@/public/styles/main.scss";
import "@/app/global.css";
import "react-toastify/ReactToastify.css";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chatvia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mont.className}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
